from __future__ import annotations

from sqlalchemy import inspect
from sqlalchemy import text
from sqlalchemy.engine import Connection


def _table_exists(connection: Connection, table_name: str) -> bool:
    inspector = inspect(connection)
    return table_name in inspector.get_table_names()


def _create_table_if_missing(connection: Connection) -> None:
    if _table_exists(connection, "lesson_contents"):
        return

    if connection.dialect.name == "postgresql":
        connection.execute(
            text(
                """
                CREATE TABLE lesson_contents (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    roadmap_node_id VARCHAR,
                    subject_id INTEGER,
                    title VARCHAR NOT NULL,
                    body_markdown VARCHAR NOT NULL,
                    youtube_url VARCHAR,
                    extra_links_json VARCHAR,
                    notes VARCHAR,
                    is_published BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL,
                    FOREIGN KEY(roadmap_node_id) REFERENCES roadmap_nodes(node_id),
                    FOREIGN KEY(subject_id) REFERENCES subjects(id),
                    CHECK (roadmap_node_id IS NOT NULL OR subject_id IS NOT NULL)
                )
                """
            )
        )
        return

    connection.execute(
        text(
            """
            CREATE TABLE lesson_contents (
                id INTEGER PRIMARY KEY,
                roadmap_node_id VARCHAR,
                subject_id INTEGER,
                title VARCHAR NOT NULL,
                body_markdown VARCHAR NOT NULL,
                youtube_url VARCHAR,
                extra_links_json VARCHAR,
                notes VARCHAR,
                is_published BOOLEAN NOT NULL DEFAULT 0,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                FOREIGN KEY(roadmap_node_id) REFERENCES roadmap_nodes(node_id),
                FOREIGN KEY(subject_id) REFERENCES subjects(id),
                CHECK (roadmap_node_id IS NOT NULL OR subject_id IS NOT NULL)
            )
            """
        )
    )


def apply(connection: Connection) -> None:
    _create_table_if_missing(connection)
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_lesson_contents_roadmap_node_id ON lesson_contents (roadmap_node_id)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_lesson_contents_subject_id ON lesson_contents (subject_id)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_lesson_contents_title ON lesson_contents (title)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_lesson_contents_is_published ON lesson_contents (is_published)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_lesson_contents_created_at ON lesson_contents (created_at)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_lesson_contents_updated_at ON lesson_contents (updated_at)"))

