from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import inspect
from sqlalchemy import text
from sqlalchemy.engine import Connection


def _table_exists(connection: Connection, table_name: str) -> bool:
    inspector = inspect(connection)
    return table_name in inspector.get_table_names()


def _column_names(connection: Connection, table_name: str) -> set[str]:
    inspector = inspect(connection)
    return {column["name"] for column in inspector.get_columns(table_name)}


def _add_column_if_missing(connection: Connection, column_name: str, sql_type: str) -> None:
    if column_name in _column_names(connection, "mock_exams"):
        return
    connection.execute(text(f"ALTER TABLE mock_exams ADD COLUMN {column_name} {sql_type}"))


def _create_mock_exam_questions_if_missing(connection: Connection) -> None:
    if _table_exists(connection, "mock_exam_questions"):
        return

    if connection.dialect.name == "postgresql":
        connection.execute(
            text(
                """
                CREATE TABLE mock_exam_questions (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    mock_exam_id INTEGER NOT NULL REFERENCES mock_exams(id),
                    question_number INTEGER NOT NULL,
                    question_code VARCHAR,
                    area VARCHAR,
                    discipline VARCHAR,
                    subject_id INTEGER REFERENCES subjects(id),
                    block_id INTEGER REFERENCES blocks(id),
                    source_type VARCHAR NOT NULL DEFAULT 'external',
                    prompt_markdown TEXT,
                    alternatives_json TEXT,
                    correct_answer VARCHAR,
                    user_answer VARCHAR,
                    is_correct BOOLEAN,
                    skipped BOOLEAN NOT NULL DEFAULT FALSE,
                    difficulty_percent FLOAT,
                    time_seconds INTEGER,
                    started_at TIMESTAMP,
                    answered_at TIMESTAMP,
                    notes TEXT,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL
                )
                """
            )
        )
    else:
        connection.execute(
            text(
                """
                CREATE TABLE mock_exam_questions (
                    id INTEGER PRIMARY KEY,
                    mock_exam_id INTEGER NOT NULL,
                    question_number INTEGER NOT NULL,
                    question_code VARCHAR,
                    area VARCHAR,
                    discipline VARCHAR,
                    subject_id INTEGER,
                    block_id INTEGER,
                    source_type VARCHAR NOT NULL DEFAULT 'external',
                    prompt_markdown TEXT,
                    alternatives_json TEXT,
                    correct_answer VARCHAR,
                    user_answer VARCHAR,
                    is_correct BOOLEAN,
                    skipped BOOLEAN NOT NULL DEFAULT 0,
                    difficulty_percent FLOAT,
                    time_seconds INTEGER,
                    started_at DATETIME,
                    answered_at DATETIME,
                    notes TEXT,
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL,
                    FOREIGN KEY(mock_exam_id) REFERENCES mock_exams(id),
                    FOREIGN KEY(subject_id) REFERENCES subjects(id),
                    FOREIGN KEY(block_id) REFERENCES blocks(id)
                )
                """
            )
        )


def apply(connection: Connection) -> None:
    if not _table_exists(connection, "mock_exams"):
        return

    timestamp_type = "TIMESTAMP" if connection.dialect.name == "postgresql" else "DATETIME"
    _add_column_if_missing(connection, "mode", "VARCHAR")
    _add_column_if_missing(connection, "status", "VARCHAR")
    _add_column_if_missing(connection, "estimated_tri_score", "FLOAT")
    _add_column_if_missing(connection, "started_at", timestamp_type)
    _add_column_if_missing(connection, "finished_at", timestamp_type)
    _add_column_if_missing(connection, "result_json", "TEXT")

    now_iso = datetime.now(timezone.utc).replace(tzinfo=None).isoformat(sep=" ")
    connection.execute(
        text(
            """
            UPDATE mock_exams
            SET mode = COALESCE(mode, 'external'),
                status = COALESCE(status, 'draft'),
                updated_at = COALESCE(updated_at, :now_value)
            """
        ),
        {"now_value": now_iso},
    )

    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exams_mode ON mock_exams (mode)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exams_status ON mock_exams (status)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exams_started_at ON mock_exams (started_at)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exams_finished_at ON mock_exams (finished_at)"))

    _create_mock_exam_questions_if_missing(connection)
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exam_questions_mock_exam_id ON mock_exam_questions (mock_exam_id)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exam_questions_question_number ON mock_exam_questions (question_number)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exam_questions_area ON mock_exam_questions (area)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exam_questions_discipline ON mock_exam_questions (discipline)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exam_questions_source_type ON mock_exam_questions (source_type)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exam_questions_is_correct ON mock_exam_questions (is_correct)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exam_questions_skipped ON mock_exam_questions (skipped)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exam_questions_started_at ON mock_exam_questions (started_at)"))
    connection.execute(text("CREATE INDEX IF NOT EXISTS ix_mock_exam_questions_answered_at ON mock_exam_questions (answered_at)"))
